class Configuration():
    sLogHeader="<ProjectName>"
    sReleaseName="Regression"
    sCountry=""
    iTotalTestCasesFail=0
    iTestcaseIDRowNo = 0;
    iScreenCounter=1;
    sSCreenNames = [];
    sLogMsg = [];
    LogMsg_Suit=[]
    sStepExecutionDate = [];
    sTCStatus = [];
    iTotalScreenCounter = [];
    sLogScreenshot  = '';
    sTestCaseLogFolder='';
    sLogScreenshotAlias='';
    sProcessSheetName = '';
    sLoginSheetName='';
    sDateInDDMMYYY='';
    sStartTime="";
    sNewTestCaseName='';
    sLoginId=''
    sTestcaseId = '';
    sTCIDWithObjective={}
    sTestCaseSheetName = '';
    sSheet_Name = None;
    column_no = 0;
    iNoOfTC=0;
    iRowNo = 0;
    iCounter = 0;
    iCount=0;
    iTotalTestCasesToRun = 0;
    iTotalTestCasesPass = 0;
    iTotalTestCasesFail = 0;
    bLogFlag = True;
    DriverFlag = False;
    iLogMsgSize = 0;
    iTCStatusSize = 0;
    iSCreenNamesSize = 0;
    iStepExecutionDateSize = 0;
    bTCExcetionTracker = True;
    bCAGPStatusFlag = True;
    sDriverFileName = "Driver File_Execution.xls";
    sFolderPath = "C:/Users/IBM_ADMIN/Desktop/Test Case Creation";
    logDirectory = "../Logs/"
    screenshotDirectory = "Logs/Screenshots/"
    sLogFilePath = "";
    screenshotDirectoryFull=''
    sScriptFolderName="";
    sLogFileName_excel = "LogFile.xlsx";
    sLogFileName_log = "LogFile.txt";
    sConsolidatedLogFileName = "ConsolidatedLogFile.xlsx";
    TCName = None;
    sTestcaseId="";
    sEndTime=None;
    TCWithStats={};
    projectpath=''
    sLogMsg=[];
    sTCStatus=[];
    arSCreenNames=[];
    iTotalScreenCounter=[];
    sStepExecutionDate=[];
    sTCWithStats={}
    def __init__(self):
        pass