#----------------------------------------------------------------------------------------
#========================================================================================
#----------------------------------------------------------------------------------------
[basic info]
#url=https://courses.letskodeit.com/practice
url=https://way2automation.com/way2auto_jquery/index.php
#url=https://deluxe-menu.com/popup-mode-sample.html
#url=https://jqueryui.com/droppable/
implicitly_wait=30
#Use Log Type as txt for logging in plain text Format. excel to generate logging in Excel format. allure to Generate Alllure Report
#Use hml for logging in HTML format.
log_type=html
# Make yes incase You need screenshot for Pass message of Failed Message 
screenshot_for_pass=yes
screenshot_for_fail=yes
# Do you want to Override the old screenshots. Mark yes or no
override_screenshot=yes
#Mention Driver File Path
driver_path=C:/Users/biswa/OneDrive/Desktop/Test Suit
#creen Names will be compared based on the below Config File
default_config_file=Configuration.ini

#----------------------------------------------------------------------------------------
#========================================================================================
#----------------------------------------------------------------------------------------
[loggers]
keys=root,detail,consolidate

[handlers]
keys=fileHandler

[formatters]
keys=simpleFormatter,resultFormatter

[logger_root]
level=DEBUG
handlers=fileHandler

[logger_detail]
level=INFO
handlers=fileHandler
qualname=detailLogger
propagate=0
[logger_consolidate]
level=INFO
handlers=fileHandler
qualname=consolidateLogger
propagate=0

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=%(simple)s
args=(r'%(logfilename)s', 'a')

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
#format=r'%(logformat)s''
datefmt=%m/%d/%Y %I:%M:%S %p

[formatter_resultFormatter]
format=%(message)s
#format=r'%(logformat)s''
datefmt=%m/%d/%Y %I:%M:%S %p